while True:
   a="1) which is our contry?"
   print(a)
   b=["a)india"   ,  "b) china" , "c)japan"  ,   "d)rushia" ]
   print(b[0],"   ",b[1])
   print(b[2],"   ",b[3])
   option=input("PUT YOUR ANS =")
   india="a"
   china="b"
   japan="c"
   rashia="d"
   if option==india:
         print("your ans is write.")
         print("you are won 1000$......")
         break
   elif option==china:
       print("your ans is wrong!!")
   elif option==japan:
       print("your ans is wrong!!")
   elif option==rashia:
       print("your ans is wrong!!")
   else:
     print("invalid option!!")

